server:
  port: 8082

#spring:
#  datasource:
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@localhost:1521/xe
#    username: scott
#    password: tiger

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/education_3top?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: tiger

  messages:
    basename: messages, errors

mybatis:
  type-aliases-package: education.top.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    education:
      top:
        web: debug

file:
  dir: D:/uploadtest/


